CREATE TABLE IF NOT EXISTS poses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  m1 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  m2 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  m3 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  m4 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  m5 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  m6 TINYINT UNSIGNED NOT NULL DEFAULT 90,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS status (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  val TINYINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO status(id,val) VALUES (1,0)
  ON DUPLICATE KEY UPDATE val=VALUES(val);
